type User {
  id: ID!
  name: String!
  email: String!
  password: String!
}

type Query {
  getUser(id: ID!): User
  getUsers: [User]!
}

input UserInput {
  name: String!
  email: String!
  password: String!
}

input UserUpdate {
  name: String
  email: String
  password: String
}

type Mutation {
  createUser(data: UserInput!): User
  updateUser(id: ID!, data: UserUpdate): User
  deleteUser(id: ID!): Boolean!
}